### ISSUE TITLE
change QuartiCal ms to URI type and test

### ISSUE THREAD

**Issue by o-smirnov** [caracal-pipeline/cult-cargo#15]
Predicated on https://github.com/caracal-pipeline/stimela/issues/209

**Comment by o-smirnov** [comment]
@sjperkins @JSKenyon are all the other dask-ms tools automatically URI-aware? If so, I should adjust the tricolour, crystallball and shadeMS schemas as well.

**Comment by sjperkins** [comment]
> @sjperkins @JSKenyon are all the other dask-ms tools automatically URI-aware? If so, I should adjust the tricolour, crystallball and shadeMS schemas as well.

They'll require relatively minor changes to support all schemas

**Comment by o-smirnov** [comment]
OK then I won't update the schemas just now. Only for QuartiCal.
