### ISSUE TITLE
`taql.update` cab fails to raise error 

### ISSUE THREAD

**Issue by JSKenyon** [caracal-pipeline/cult-cargo#29]
While testing the rrat pipeline, the `subtract_model` step was failing due to a lack of write permissions. However, the failure was not caught by stimela i.e. it didn't crash/warn the user. The message was as follows:
```
# Error in TaQL command: 'using style python update /home/kenyon/ATA_experiments/original_data/SN2023ixf_noauto_1GC.ms set CORRECTED_DATA=SELFCAL2_DATA-MODEL_DATA'                 
#   Table /home/kenyon/ATA_experiments/original_data/SN2023ixf_noauto_1GC.ms cannot be opened for read/write 
```

I will open a PR with the fix shortly.

**Comment by o-smirnov** [comment]
Actually the PR just fixes the write permissions. We still need to add wranglers to the cab to catch the actual error and raise it as such with stimela. Same goes for the casa cabs.

**Comment by JSKenyon** [comment]
Thanks - had meant to reopen it myself.
